// <auto-generated />
namespace OnlineMark.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dell_pass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dell_pass));
        
        string IMigrationMetadata.Id
        {
            get { return "201611201458198_dell_pass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
